codecov:
  require_ci_to_pass: true

component_management:
  individual_components:
    - component_id: generated_client
      name: generated-client
      paths:
        - internal/openapi/generated/**
        - internal/models/generated/**

    - component_id: internal_api
      name: internal-api
      flag_regexes:
        - ^combined_scoped$
      paths:
        - internal/**

    - component_id: cmd
      name: cmd
      flag_regexes:
        - ^combined_scoped$
      paths:
        - cmd/**

    - component_id: tools
      name: tools
      paths:
        - tools/**

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        flags:
          - combined_scoped
        paths:
          - internal/**
          - "!internal/openapi/generated/**"
          - "!internal/models/generated/**"
        target: auto
      combined_raw:
        flags:
          - combined_raw
        paths:
          - cmd/**
          - internal/**
        target: auto
      combined_scoped:
        flags:
          - combined_scoped
        paths:
          - cmd/**
          - internal/**
          - "!internal/openapi/generated/**"
          - "!internal/models/generated/**"
        target: auto
    patch:
      default:
        flags:
          - combined_scoped
        paths:
          - internal/**
          - "!internal/openapi/generated/**"
          - "!internal/models/generated/**"
        target: auto
      combined_raw:
        flags:
          - combined_raw
        paths:
          - cmd/**
          - internal/**
        target: auto
      combined_scoped:
        flags:
          - combined_scoped
        paths:
          - cmd/**
          - internal/**
          - "!internal/openapi/generated/**"
          - "!internal/models/generated/**"
        target: auto

ignore:
  - docs/**
  - docker/**
  - tests/**
