codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        flags:
          - combined_scoped
        paths:
          - cmd/**
          - internal/**
          - "!internal/openapi/generated/**"
          - "!internal/models/generated/bitbucket_types.gen.go"
        target: auto
      combined_raw:
        flags:
          - combined_raw
        paths:
          - cmd/**
          - internal/**
        target: auto
      combined_scoped:
        flags:
          - combined_scoped
        paths:
          - cmd/**
          - internal/**
          - "!internal/openapi/generated/**"
          - "!internal/models/generated/bitbucket_types.gen.go"
        target: auto
    patch:
      default:
        flags:
          - combined_scoped
        paths:
          - cmd/**
          - internal/**
          - "!internal/openapi/generated/**"
          - "!internal/models/generated/bitbucket_types.gen.go"
        target: auto
      combined_raw:
        flags:
          - combined_raw
        paths:
          - cmd/**
          - internal/**
        target: auto
      combined_scoped:
        flags:
          - combined_scoped
        paths:
          - cmd/**
          - internal/**
          - "!internal/openapi/generated/**"
          - "!internal/models/generated/bitbucket_types.gen.go"
        target: auto

ignore:
  - docs/**
  - docker/**
  - tests/**
