version: '3'

vars:
  OAPI_CODEGEN_VERSION: v2.4.1
  BITBUCKET_OPENAPI_URL: https://dac-static.atlassian.com/server/bitbucket/9.4.swagger.v3.json?_v=1.637.27
  BITBUCKET_OPENAPI_TARGET: docs/reference/atlassian/bitbucket-9.4-openapi.json
  BITBUCKET_OPENAPI_TMP: .tmp/bitbucket-9.4-openapi.json
  BITBUCKET_OPENAPI_SANITIZED_TMP: .tmp/bitbucket-9.4-openapi.sanitized.json

tasks:
  default:
    desc: Show available tasks
    cmd: task --list

  docs:refresh-openapi:
    desc: Refresh vendored Atlassian Bitbucket 9.4 OpenAPI reference
    cmds:
      - mkdir -p .tmp docs/reference/atlassian
      - curl -fsSL '{{.BITBUCKET_OPENAPI_URL}}' -o '{{.BITBUCKET_OPENAPI_TMP}}'
      - python3 -c "import json; d=json.load(open('.tmp/bitbucket-9.4-openapi.json', 'r', encoding='utf-8')); assert d.get('openapi') == '3.0.1', 'unexpected openapi version'; assert d.get('info', {}).get('version') == '9.4', 'unexpected API version'; print('validated openapi paths=' + str(len(d.get('paths', {}))))"
      - cp '{{.BITBUCKET_OPENAPI_TMP}}' '{{.BITBUCKET_OPENAPI_TARGET}}'

  models:generate:
    desc: Generate Go models from vendored Bitbucket 9.4 OpenAPI spec
    cmds:
      - mkdir -p internal/models/generated
      - go run ./tools/openapi-sanitize -in docs/reference/atlassian/bitbucket-9.4-openapi.json -out {{.BITBUCKET_OPENAPI_SANITIZED_TMP}}
      - go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@{{.OAPI_CODEGEN_VERSION}} -config tools/oapi-codegen/bitbucket-types.yaml {{.BITBUCKET_OPENAPI_SANITIZED_TMP}}
      - go run ./tools/oapi-fix-generated -file internal/models/generated/bitbucket_types.gen.go
      - gofmt -w internal/models/generated/bitbucket_types.gen.go

  models:verify:
    desc: Verify generated models are up to date
    cmds:
      - task: models:generate
      - git diff --exit-code -- internal/models/generated/bitbucket_types.gen.go

  client:generate:
    desc: Generate Go OpenAPI client from vendored Bitbucket 9.4 OpenAPI spec
    cmds:
      - mkdir -p internal/openapi/generated
      - go run ./tools/openapi-sanitize -in docs/reference/atlassian/bitbucket-9.4-openapi.json -out {{.BITBUCKET_OPENAPI_SANITIZED_TMP}}
      - go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@{{.OAPI_CODEGEN_VERSION}} -config tools/oapi-codegen/bitbucket-client.yaml {{.BITBUCKET_OPENAPI_SANITIZED_TMP}}
      - gofmt -w internal/openapi/generated/bitbucket_client.gen.go

  client:verify:
    desc: Verify generated OpenAPI client is up to date
    cmds:
      - task: client:generate
      - git diff --exit-code -- internal/openapi/generated/bitbucket_client.gen.go

  quality:validate-decisions:
    desc: Validate ADR decision records with Go validator
    cmd: go run ./tools/adr-validator --validate

  quality:check:
    desc: Run core quality checks
    deps:
      - quality:validate-decisions
      - test:unit

  test:unit:
    desc: Run Go unit tests
    cmd: go test ./cmd/... ./internal/... ./tools/...

  test:live:
    desc: Run live integration tests against local Bitbucket stack
    cmd: go test -tags=live ./tests/integration/live

  stack:up:
    desc: Start local Bitbucket + Postgres stack
    cmd: docker compose -f docker/compose.yml up -d

  stack:down:
    desc: Stop local Bitbucket + Postgres stack
    cmd: docker compose -f docker/compose.yml down

  stack:restart:
    desc: Restart local Bitbucket + Postgres stack
    cmds:
      - task: stack:down
      - task: stack:up

  stack:status:
    desc: Show local stack status
    cmd: docker compose -f docker/compose.yml ps

  stack:logs:
    desc: Tail Bitbucket service logs
    cmd: docker compose -f docker/compose.yml logs -f bitbucket
