name: bitbucket-server-cli

services:
  postgres:
    image: postgres:17
    container_name: bb-postgres
    environment:
      POSTGRES_DB: bitbucket
      POSTGRES_USER: bitbucket
      POSTGRES_PASSWORD: bitbucket
    ports:
      - "5432:5432"
    volumes:
      - bb-postgres-data:/var/lib/postgresql/data

  bitbucket:
    build:
      context: ./custom-bitbucket
    image: atlassian/bitbucket:9.4.16-faketime
    container_name: bb-bitbucket
    depends_on:
      - postgres
    env_file:
      - ../.env
    environment:
      LD_PRELOAD: /usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1
      FAKETIME: "@2026-03-01 00:00:00"
      JDBC_DRIVER: org.postgresql.Driver
      JDBC_URL: jdbc:postgresql://postgres:5432/bitbucket
      JDBC_USER: bitbucket
      JDBC_PASSWORD: bitbucket
      JVM_MINIMUM_MEMORY: 1g
      JVM_MAXIMUM_MEMORY: 2g
      BITBUCKET_LICENSE_KEY: ${BITBUCKET_LICENSE_KEY}
    ports:
      - "7990:7990"
      - "7999:7999"
    volumes:
      - bb-bitbucket-data:/var/atlassian/application-data/bitbucket

volumes:
  bb-postgres-data:
  bb-bitbucket-data:
