package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestExportCommandReferenceWritesMarkdown(t *testing.T) {
	outputPath := filepath.Join(t.TempDir(), "commands.md")

	if err := exportCommandReference(outputPath); err != nil {
		t.Fatalf("exportCommandReference failed: %v", err)
	}

	raw, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("read generated file failed: %v", err)
	}

	content := string(raw)
	if !strings.Contains(content, "# All Commands") {
		t.Fatalf("missing document title")
	}
	if !strings.Contains(content, "This page is generated by `task docs:export-command-reference`.") {
		t.Fatalf("missing generated banner")
	}
	if !strings.Contains(content, "## `bb`") {
		t.Fatalf("missing root command section")
	}
	if !strings.Contains(content, "## `bb auth`") {
		t.Fatalf("missing expected subcommand section")
	}
	if !strings.HasSuffix(content, "\n") {
		t.Fatalf("expected trailing newline")
	}
}

func TestExportCommandReferenceReturnsErrorForInvalidPath(t *testing.T) {
	base := t.TempDir()
	filePath := filepath.Join(base, "not-a-directory")
	if err := os.WriteFile(filePath, []byte("x"), 0o600); err != nil {
		t.Fatalf("setup failed: %v", err)
	}

	err := exportCommandReference(filepath.Join(filePath, "commands.md"))
	if err == nil {
		t.Fatal("expected error for invalid path")
	}
	if !strings.Contains(err.Error(), "create command docs directory") {
		t.Fatalf("unexpected error: %v", err)
	}
}
