package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/vriesdemichael/bitbucket-server-cli/internal/cli"
)

func main() {
	outputPath := flag.String("out", "docs/site/reference/commands/index.md", "Path to generated Markdown command reference")
	flag.Parse()

	if err := exportCommandReference(*outputPath); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func exportCommandReference(outputPath string) error {
	root := cli.NewRootCommand()
	commands := collectVisibleCommands(root)

	sort.Slice(commands, func(i, j int) bool {
		return commands[i].CommandPath() < commands[j].CommandPath()
	})

	var content strings.Builder
	content.WriteString("# All Commands\n\n")
	content.WriteString("This page is generated by `task docs:export-command-reference`. Do not edit manually.\n\n")
	content.WriteString(fmt.Sprintf("Generated command entries: %d\n\n", len(commands)))

	for _, command := range commands {
		helpText, err := renderHelp(command)
		if err != nil {
			return fmt.Errorf("render help for %q: %w", command.CommandPath(), err)
		}

		content.WriteString(fmt.Sprintf("## `%s`\n\n", command.CommandPath()))
		if short := strings.TrimSpace(command.Short); short != "" {
			content.WriteString(short)
			content.WriteString("\n\n")
		}

		content.WriteString("```text\n")
		content.WriteString(helpText)
		if !strings.HasSuffix(helpText, "\n") {
			content.WriteString("\n")
		}
		content.WriteString("```\n\n")
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return fmt.Errorf("create command docs directory: %w", err)
	}

	payload := strings.TrimRight(content.String(), "\n") + "\n"
	if err := os.WriteFile(outputPath, []byte(payload), 0o644); err != nil {
		return fmt.Errorf("write command docs: %w", err)
	}

	fmt.Printf("wrote %s\n", outputPath)
	return nil
}

func collectVisibleCommands(root *cobra.Command) []*cobra.Command {
	commands := []*cobra.Command{root}

	var walk func(command *cobra.Command)
	walk = func(command *cobra.Command) {
		for _, child := range command.Commands() {
			if child.Hidden {
				continue
			}
			commands = append(commands, child)
			walk(child)
		}
	}

	walk(root)
	return commands
}

func renderHelp(command *cobra.Command) (string, error) {
	var buffer bytes.Buffer
	command.SetOut(&buffer)
	command.SetErr(&buffer)

	if err := command.Help(); err != nil {
		return "", err
	}

	return strings.TrimRight(buffer.String(), "\n"), nil
}
